#!/usr/bin/env node
import {spawn} from "node:child_process";
import crypto from "node:crypto";
import readline from "node:readline";
import {SyntheticDriver} from "./synthetic-driver.mjs";

async function explore(call){ await call("reset",{seed:7,fixture:"stale-search"}); const seen=new Set(), transitions=[]; const traces=[[]]; let failure=null; while(traces.length){ const trace=traces.shift(); await call("reset",{seed:7,fixture:"stale-search"}); let snap; for(const a of trace) snap=(await call("execute",{action:a})).snapshot; snap??=await call("reset",{seed:7,fixture:"stale-search"}); if(seen.has(snap.fingerprint)) continue; seen.add(snap.fingerprint); const acts=await call("actions",{}); for(const a of acts){ await call("reset",{seed:7,fixture:"stale-search"}); let before; for(const t of trace) before=(await call("execute",{action:t})).snapshot; before??=await call("reset",{seed:7,fixture:"stale-search"}); const after=(await call("execute",{action:a})).snapshot; transitions.push([before.fingerprint,a.id,after.fingerprint]); const next=[...trace,a]; const replay=await call("replay",{trace:next}); if(replay.property && !failure) failure={property:replay.property,trace:next}; if(next.length<4) traces.push(next); } }
 if(failure){ let changed=true; while(changed){ changed=false; for(let i=0;i<failure.trace.length;i++){ const candidate=failure.trace.filter((_,j)=>j!==i); const r=await call("replay",{trace:candidate}); if(r.property===failure.property){ failure.trace=candidate; changed=true; break; } } } }
 const report={states:seen.size,transitions:transitions.length,property:failure?.property,trace:failure?.trace.map(x=>x.id)}; report.semanticHash=crypto.createHash("sha256").update(JSON.stringify(report)).digest("hex"); return report; }
async function direct(){ const d=new SyntheticDriver(); return explore(async(m,p)=>{ if(m==="reset") return d.reset(p.seed,p.fixture); if(m==="actions") return d.actions(); if(m==="execute") return d.execute(p.action); if(m==="replay") return d.replay(p.trace); }); }
async function jsonl(){ const child=spawn(process.execPath,[new URL("./synthetic-driver.mjs",import.meta.url).pathname]); const rl=readline.createInterface({input:child.stdout}); const waits=new Map(); rl.on("line",l=>{const r=JSON.parse(l); waits.get(r.id)(r); waits.delete(r.id)}); let id=0; const call=(method,params)=>new Promise((resolve,reject)=>{const n=++id; waits.set(n,r=>r.error?reject(new Error(r.error.message)):resolve(r.result)); child.stdin.write(JSON.stringify({protocolVersion:"1.0",id:n,method,params})+"\n")}); const report=await explore(call); child.kill(); return report; }
const [a,b]=await Promise.all([direct(),jsonl()]); if(JSON.stringify(a)!==JSON.stringify(b)) throw new Error(`parity mismatch\n${JSON.stringify(a)}\n${JSON.stringify(b)}`); if(JSON.stringify(a.trace)!==JSON.stringify(["type:a","type:ab","deliver:1"])) throw new Error(`unexpected shrink ${JSON.stringify(a.trace)}`); console.log(JSON.stringify({ok:true,direct:a,jsonl:b}));
